config/routes.rb
Tfpullrequests::Application.routes.draw do
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unprocessable'
  get '/500', to: 'errors#internal'

  get '/locale/:locale', to: 'dashboards#locale', as: :locale
  resources :gifts, except: [:show]
  resources :users, only: [:show, :index]

  resources :organisations, only: [:show, :index]

  get '/mergers', to: 'users#mergers', as: :mergers
  get '/users/:id', to: 'users#show'
  get '/users/unsubscribe/:token', to: 'users#unsubscribe', as: :user_unsubscribe

  resources :events

  resources :projects do
    collection do
      get :autofill
      post :claim
    end
    member do
      put :reactivate
    end
  end

  resources :contributions do
    collection do
      get :meta
    end
  end

  resources :pull_requests, only: [:index], controller: 'contributions' do
    collection do
      get :meta
    end
  end

  resource :dashboard, only: [:show, :destroy] do
    member do
      get :delete
      delete :destroy
    end
  end
  resource :pull_request_download, only: :create

  get '/resend_confirmation', to: 'dashboards#resend_confirmation_email', as: 'resend_confirmation'
  get '/confirm/:confirmation_token', to: 'dashboards#confirm_email', as: 'confirm_email'

  get '/preferences', to: 'dashboards#preferences', as: 'preferences'
  patch '/preferences/update', to: 'dashboards#update_preferences', as: 'update_preferences'
  get :my_suggestions, to: 'users#projects', as: :my_suggestions

  get '/login',  to: 'sessions#new',     as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/contributors/map', to: 'contributor_map#show'

  get '/auth/twitter/callback',    to: 'twitter#authorize'
  delete '/twitter/remove',         to: 'twitter#remove'

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get '/auth/failure',             to: 'sessions#failure'


  get 'about', to: 'static#about'
  get 'sponsors' => redirect('/about') # old sponsors url
  get 'humans', to: 'static#humans'
  get 'api', to: 'static#api'
  get 'contributing', to: 'static#contributing'
  get '2018', to: 'static#2018'

  get '/unsubscribe', to: 'unsubscribes#new', as: :unsubscribe
  post '/unsubscribe', to: 'unsubscribes#create'

  resources :languages, only: [:show] do
    member do
      get :projects
      get :pull_requests
      get :users
    end
  end

  root to: 'static#homepage'

  get '/email' => redirect('/preferences') # old preferences URL

  get '/:id' => redirect('/users/%{id}') # User public vanity url, must be lowest priority

  namespace :admin do
    post '/dasher', to: 'dasher#new_pull_request'
    resources :projects, only: [:index, :edit, :update, :destroy]
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :set_language

  def show
    @projects = Project.active.by_language(@language).limit(20)
    @users = User.order('contributions_count desc').by_language(@language).limit(200).sample(45)
    @contributions = Contribution.by_language(@language).year(current_year).latest(5)
  end

  def projects
    @projects = Project.active.by_language(@language).page(params[:page])
  end

  def pull_requests
    @contributions = Contribution.by_language(@language).year(current_year).page(params[:page])

    render 'contributions/index'
  end

  def users
    @users = User.order('contributions_count desc, nickname asc').by_language(@language).page(params[:page])

    render 'users/index'
  end

  private

  def set_language
    @language = Project::LANGUAGES.detect { |lan| lan.downcase.eql? language.downcase }

    fail(ActionController::RoutingError, "#{language} is not a valid language") if @language.nil?
  end

  def language
    params[:id]
  end
end

app/views/languages/projects.html.erb
<div class="row-fluid clearfix" id="projects">
  <h3>
    <%= t("language.projects.count", count: number_with_delimiter(project_count_for_language), language: @language) %>
    <%= link_to t("language.projects.suggest", language: @language), new_project_path(language: @language), :class => 'btn pull-right' %>
  </h3>
  <div class="row-fluid clearfix">
    <div class="span12">
      <%= render @projects %>
    </div>
    <%= paginate @projects %>
  </div>
</div>

app/views/languages/projects.js.erb
  (function($projects) {
    var $new = $("<%= escape_javascript(render(@projects)) %>");

    $projects.find('.span12')
      .html($new)

    $(".more")
      .replaceWith(
        "#{escape_javascript(link_to_next_page @projects,
                                               t('more'),
                                               remote: true,
                                               class: 'btn btn-success more')}"
      );
  })($("#projects"));

app/views/languages/show.html.erb
<h2><%= @language %></h2>
<% if @users.any? %>
  <div class="row clearfix" id="users">
    <div class="col-md-12">
      <h3>
        <%= t("language.contributors.count", count: number_with_delimiter(user_count), language: @language) %>
        <%= link_to t("view_all"), users_language_path(@language.downcase), :class => 'btn btn-default' %>
        <ul class="avatar-list clearfix">
          <%= render @users %>
        </ul>
      </h3>
    </div>
  </div>
<% end %>
<% if @contributions.any? %>
  <div class="row clearfix" id="contributions">
    <div class="col-md-12">
      <h3>
        <%= t("language.pull_requests.latest.count", count: number_with_delimiter(contribution_count_for_language), language: @language) %>
        <%= link_to t("view_all"), pull_requests_language_path(@language.downcase), :class => 'btn btn-default pull-right' %>
      </h3>
      <%= render @contributions, cache: true %>
    </div>
  </div>
<% end %>
<% if @projects.any? %>
  <div class="row clearfix" id="projects">
    <div class="col-md-12">
      <h3>
        <%= t("language.projects_count", count: number_with_delimiter(project_count_for_language), language: @language) %>
        <%= link_to t("language.projects.suggest", language: @language), new_project_path(language: @language.downcase), :class => 'btn btn-default pull-right' %>
        <%= link_to t("view_all"), projects_language_path(@language.downcase), :class => 'btn btn-default pull-right' %>
      </h3>
      <%= render @projects %>
    </div>
  </div>
<% end %>