config/routes.rb
Tfpullrequests::Application.routes.draw do
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unprocessable'
  get '/500', to: 'errors#internal'

  get '/locale/:locale', to: 'dashboards#locale', as: :locale
  resources :gifts, except: [:show]
  resources :users, only: [:show, :index]

  resources :organisations, only: [:show, :index]

  get '/mergers', to: 'users#mergers', as: :mergers
  get '/users/:id', to: 'users#show'
  get '/users/unsubscribe/:token', to: 'users#unsubscribe', as: :user_unsubscribe

  resources :events

  resources :projects do
    collection do
      get :autofill
      post :claim
    end
    member do
      put :reactivate
    end
  end

  resources :contributions do
    collection do
      get :meta
    end
  end

  resources :pull_requests, only: [:index], controller: 'contributions' do
    collection do
      get :meta
    end
  end

  resource :dashboard, only: [:show, :destroy] do
    member do
      get :delete
      delete :destroy
    end
  end
  resource :pull_request_download, only: :create

  get '/resend_confirmation', to: 'dashboards#resend_confirmation_email', as: 'resend_confirmation'
  get '/confirm/:confirmation_token', to: 'dashboards#confirm_email', as: 'confirm_email'

  get '/preferences', to: 'dashboards#preferences', as: 'preferences'
  patch '/preferences/update', to: 'dashboards#update_preferences', as: 'update_preferences'
  get :my_suggestions, to: 'users#projects', as: :my_suggestions

  get '/login',  to: 'sessions#new',     as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/contributors/map', to: 'contributor_map#show'

  get '/auth/twitter/callback',    to: 'twitter#authorize'
  delete '/twitter/remove',         to: 'twitter#remove'

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get '/auth/failure',             to: 'sessions#failure'


  get 'about', to: 'static#about'
  get 'sponsors' => redirect('/about') # old sponsors url
  get 'humans', to: 'static#humans'
  get 'api', to: 'static#api'
  get 'contributing', to: 'static#contributing'
  get '2018', to: 'static#2018'

  get '/unsubscribe', to: 'unsubscribes#new', as: :unsubscribe
  post '/unsubscribe', to: 'unsubscribes#create'

  resources :languages, only: [:show] do
    member do
      get :projects
      get :pull_requests
      get :users
    end
  end

  root to: 'static#homepage'

  get '/email' => redirect('/preferences') # old preferences URL

  get '/:id' => redirect('/users/%{id}') # User public vanity url, must be lowest priority

  namespace :admin do
    post '/dasher', to: 'dasher#new_pull_request'
    resources :projects, only: [:index, :edit, :update, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Concerns::Twitter

  attr_writer :gift_factory

  has_many :contributions,       dependent: :destroy
  has_many :skills,              dependent: :destroy
  has_many :gifts,               dependent: :destroy
  has_many :aggregation_filters, dependent: :destroy

  has_many :projects
  has_many :events

  has_and_belongs_to_many :organisations

  has_many :merged_contributions, class_name: 'Contribution', foreign_key: :merged_by_id, primary_key: :uid

  scope :by_language, ->(language) { joins(:skills).where('lower(language) = ?', language.downcase) }
  scope :with_any_contributions, -> { where('users.contributions_count > 0') }
  scope :random, -> { order(Arel.sql("RANDOM()")) }

  paginates_per 96

  accepts_nested_attributes_for :skills, reject_if: proc { |attributes| !Project::LANGUAGES.include?(attributes['language']) }

  before_save :check_email_changed
  before_validation :generate_unsubscribe_token
  after_create :download_contributions, :estimate_skills, :download_user_organisations

  validates :email, presence: true, if: :send_regular_emails?
  validates :email, format: { with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/, allow_blank: true, on: :update }
  validates :unsubscribe_token, presence: true, uniqueness: true

  def self.find_by_nickname!(nickname)
    where(['lower(nickname) =?', nickname.downcase]).first!
  end

  def self.find_by_unsubscribe_token(token)
    where(unsubscribe_token: token).take
  end

  def self.find_by_login(login)
    where(['lower(nickname) =? OR lower(email) =?', login.downcase, login.downcase]).take
  end

  def self.create_from_auth_hash(hash)
    create!(AuthHash.new(hash).user_info)
  end

  def self.mergers(year = Tfpullrequests::Application.current_year)
    joins(:merged_contributions).
      where('EXTRACT(year FROM contributions.created_at) = ?', year).
      group('users.id').
      select("users.*, count(contributions.id) AS merged_contributions_count")
  end

  def assign_from_auth_hash(hash)
    # do not update the email address in case the user has updated their
    # email prefs and used a new email
    ignored_fields = %i(email name blog)
    update(AuthHash.new(hash).user_info.except(*ignored_fields))
  end

  def self.find_by_auth_hash(hash)
    conditions = AuthHash.new(hash).user_info.slice(:provider, :uid)
    where(conditions).first
  end

  def self.contributors
    @contributors ||= begin
      contribs = load_user.github_client.contributors('24pullrequests/24pullrequests')
      where_nickname_in(contribs.map(&:login))
    end
  end

  def self.admins
    @admins ||= where_nickname_in(organization_members.map(&:login))
  end

  def self.load_user
    user = User.order('created_at desc').limit(50).sample(1).first
    return user if user.high_rate_limit?
    load_user
  end

  def self.organization_members
    load_user.github_client.organization_members('24pullrequests')
  end

  def self.where_nickname_in(nicknames)
    result = where('nickname in (?)', nicknames)
    nicknames.compact.map { |c| result.find { |u| u.nickname == c } }.compact
  end

  delegate :high_rate_limit?, to: :github_client

  def github_profile
    "https://github.com/#{nickname}" if nickname.present?
  end

  def avatar_url(size = 80)
    "https://avatars.githubusercontent.com/u/#{uid}?size=#{size}"
  end

  def suggested_projects
    Project.active.where(main_language: languages).not_owner(nickname)
  end

  def estimate_skills
    return if ENV['GITHUB_KEY'].blank?
    (Project::LANGUAGES & repo_languages).each do |language|
      skills.create(language: language)
    end
  end

  def languages
    skills.any? ? skills.order(:language).pluck(:language) : Project::LANGUAGES
  end

  def github_client
    @github_client ||= GithubClient.new(nickname, token)
  end

  def confirmed?
    !!confirmed_at
  end

  def unconfirmed?
    !confirmed? && email_frequency != 'none' && email.present?
  end

  def confirm!
    if email.present? && !confirmed?
      return update(confirmation_token: nil,
                    confirmed_at:       Time.zone.now.utc)
    elsif confirmed?
      errors.add(:email, :already_confirmed)
    else
      errors.add(:email, :required_for_confirmation)
    end
    false
  end

  def generate_confirmation_token
    self.confirmation_token = loop do
      token = SecureRandom.urlsafe_base64
      break token unless User.where(confirmation_token: token).exists?
    end
  end

  def send_confirmation_email
    generate_confirmation_token
    save
    ConfirmationMailer.confirmation(self).deliver_now
  end

  def new_gift(attrs = {})
    GiftFactory.create!(self, gift_factory, attrs)
  end

  def gift_factory
    @gift_factory ||= Gift.public_method(:new)
  end

  def gift_for(date)
    Gift.find(id, date)
  end

  def ungifted_dates
    Gift.giftable_dates - gifts.pluck(:date)
  end

  def gift_unspent_contributions!
    return if ungifted_dates.empty?
    contributions = unspent_contributions.slice(0, ungifted_dates.count)
    contributions.each do |contribution|
      new_gift(contribution: contribution).save
    end
  end

  def send_regular_emails?
    %w(daily weekly).include?(email_frequency)
  end

  def to_param
    nickname
  end

  def download_user_organisations(access_token = token)
    orgs = Downloader.new(self, access_token).get_organisations
    orgs.each(&:update_contribution_count)
  end

  def download_contributions(access_token = token)
    Downloader.new(self, access_token).get_pull_requests
  end

  def unspent_contributions
    gifted_contributions = gifts.map(&:contribution)
    contributions_ignoring_organisations.year(Tfpullrequests::Application.current_year).reject { |pr| gifted_contributions.include?(pr) }
  end

  def needs_setup?
    email_frequency.nil?
  end

  def admin?
    @admin ||= User.admins.include?(self)
  end

  def send_thank_you_email_on_24
    return unless contributions_count >= 24 && !thank_you_email_sent
    ThankYouMailer.thank_you(self).deliver_later
    update_column(:thank_you_email_sent, true)
  end

  def update_contribution_count
    update_attribute(:contributions_count, contributions.year(Tfpullrequests::Application.current_year).for_aggregation.count)
  end

  def ignored_organisations_string
    (ignored_organisations || []).join(", ")
  end

  def ignored_organisations_string= organisations_string
    self.ignored_organisations = (organisations_string || "")
      .split(",")
      .collect(&:strip)
      .compact
  end

  def contributions_ignoring_organisations
    contributions.excluding_organisations(ignored_organisations)
  end

  def unsubscribe!
    self.email_frequency = 'none'
    save
  end

  private

  def repo_languages
    @repo_languages ||= github_client.user_repository_languages
  end

  def check_email_changed
    return unless email_changed? && email.present?

    generate_confirmation_token
    self.confirmed_at = nil

    ConfirmationMailer.confirmation(self).deliver_now
  end

  def generate_unsubscribe_token
    self.unsubscribe_token ||= SecureRandom.uuid
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_logged_in, only: [:projects]

  respond_to :html, :json
  respond_to :js, only: [:index, :mergers]

  def index
    @users = User.order('contributions_count desc, nickname asc').page params[:page]
    respond_with @users
  end

  def show
    @user      = User.find_by_nickname!(params[:id])
    @calendar  = Calendar.new(Gift.giftable_dates(current_year), @user.gifts.year(current_year))
    @merged_contributions = @user.merged_contributions.year(current_year).latest(nil)
    respond_with @user
  end

  def projects
    @projects = current_user.projects.order('inactive desc')
  end

  def mergers
    @users = User.mergers(current_year).order("merged_contributions_count DESC").page params[:page]
    respond_with @users
  end

  def unsubscribe
    @user = User.find_by_unsubscribe_token(params[:token])
    if @user
      @user.unsubscribe!
      flash[:notice] = t('unsubscribe.success')
    else
      flash[:notice] = t('unsubscribe.invalid_token')
    end
    redirect_to root_path
  end
end

app/views/users/_calendar.html.erb
<ol class="unstyled clearfix calendar-inner">
  <% 1.upto(calendar.start_padding) do %>
    <li class="calendar-day calendar-padding"></li>
  <% end %>
  <% calendar.each_day do |date, gift| %>
    <li class="<%= ("gifted" if gift.present?) %> calendar-day">
      <% if gift.present? && gift.user == current_user %>
        <div class="remove-gift">
          <%= link_to raw("&times;"), gift_path(gift), :title => "Remove gift", :method => :delete, "data-confirm" => "Remove this gift?" %>
        </div>
      <% end %>
      <span class="<%= date == Time.zone.today ? 'calendar-mday calendar-mday-today' : 'calendar-mday' %>">
        <span class="visible-xs-inline">> 12/</span>
        <%= date.mday %>
      </span>
      <% if gift.present? %>
        <%= link_to gift.contribution_title, gift.contribution_issue_url, :target => :_blank %>
      <% end %>
    </li>
  <% end %>
  <li class="calendar-day calendar-christmas">
    <div class="calendar-inner">
      <span class="calendar-mday">
        <span class="visible-xs-inline">> 12/</span>
        25
      </span>
      <%= octicon "star", :class => "festive-star" %>
      <%= t("happy_holidays") %>
    </div>
  </li>
</ol>

app/views/users/_contribution.html.erb
<%= cache contribution do %>
  <div class="contribution row-fluid clearfix">
    <div class="span12">
      <h4>
        <% if contribution.pull_request? %>
          <%= link_to contribution.title, contribution.issue_url, :target => :_blank %>
        <% else %>
          <%= link_to 'Contributed', contribution%>
        <% end %>

        <span class="meta">
          to
          <% if contribution.pull_request? %>
            <%= link_to contribution.repo_name, "https://github.com/#{contribution.repo_name}", :target => :_blank %>
          <% else %>
            <%= link_to_if contribution.issue_url.present?, contribution.repo_name, contribution.issue_url, :target => :_blank %>
          <% end %>
          <small>
            <abbr class="timeago" title="<%= contribution.created_at.iso8601 %>">
              <%= contribution.created_at %>
            </abbr>
          </small>
          <% if contribution.language.present? %>
            <div class="language label label-info pull-right">
              <%= link_to contribution.language, language_path(contribution.language) %>
            </div>
          <% end %>
        </span>
      </h4>
      <p>
        <div class="js-emoji">
          <%= truncate contribution.body, :length => 300 %>
        </div>
      </p>
    </div>
  </div>
<% end %>

app/views/users/_merger.html.erb
<li class="avatar-cell">
  <%= link_to user_path(user.nickname), class: "avatar-link" do %>
    <%= image_tag(user.avatar_url(200), alt: user.nickname, class: "avatar-img") %>
    <div class="username"><%= user.nickname %></div>
    <span class="pr-badge">
      <%= octicon "git-pull-request", :height => 9 %>
      <%= user.merged_contributions_count %>
    </span>
  <% end %>
</li>

app/views/users/_user.html.erb
<li class="avatar-cell">
  <%= link_to user_path(user.nickname), class: "avatar-link" do %>
    <%= image_tag(user.avatar_url(200), alt: user.nickname, class: "avatar-img") %>
    <div class="username"><%= user.nickname %></div>
    <span class="pr-badge">
      <%= octicon "git-pull-request", :height => 9 %>
      <%= user.contributions_count %>
    </span>
  <% end %>
</li>

app/views/users/index.html.erb
<div class="row clearfix fullwidth-panel">
  <div class="col-md-12">
    <h3>
      <%= number_with_delimiter user_count %>
      <% if @language %>
        <%= t("contributors_using_language", language: @language) %>
      <% else %>
        <%= t("contributors_involved") %>
      <% end %>
    </h3>
    <div class="js-user-pagination">
      <ul class="clearfix avatar-list avatar-list-lg js-user-list">
        <%= render @users %>
      </ul>
      <%= link_to_next_page @users, t("more"), params: params.permit(:year), remote: true, class: 'btn btn-success more' %>
    </div>
  </div>
</div>

app/views/users/index.js.erb
(function($users) {
  var $new = $("<%= escape_javascript(render(@users)) %>").find("a[rel=tooltip]").tooltip().end();

  $users.find('.js-user-list')
        .append($new)

  $users.find(".more")
        .replaceWith(
          "<%= escape_javascript(link_to_next_page @users,
                                                 t('more'),
                                                 params: params.permit(:year),
                                                 remote: true,
                                                 class: 'btn btn-success more') %>"
        );
})($(".js-user-pagination"));

app/views/users/mergers.html.erb
<div class="row clearfix fullwidth-panel">
  <div class="col-md-12">
    <h3>
      <%= number_with_delimiter @users.total_count %>
      Maintainers who've merged pull requests in <%= current_year %>
    </h3>
    <div class="js-user-pagination">
      <ul class="clearfix avatar-list avatar-list-lg js-user-list">
        <%= render partial: 'merger', collection: @users, as: :user %>
      </ul>
      <%= link_to_next_page @users, t("more"), params: params.permit(:year), remote: true, class: 'btn btn-success more' %>
    </div>
  </div>
</div>

app/views/users/mergers.js.erb
(function($users) {
  var $new = $("<%= escape_javascript(render(partial: 'merger', collection: @users, as: :user)) %>").find("a[rel=tooltip]").tooltip().end();

  $users.find('.js-user-list')
        .append($new)

  $users.find(".more")
        .replaceWith(
          "<%= escape_javascript(link_to_next_page @users,
                                                 t('more'),
                                                 params: params.permit(:year),
                                                 remote: true,
                                                 class: 'btn btn-success more') %>"
        );
})($(".js-user-pagination"));

app/views/users/projects.html.erb
<h3>
  <%= t("suggestions.title") %>
</h3>
<hr/>
<div class="row-fluid" id="projects">
  <% if @projects.any? %>
    <%= render partial: 'projects/editable_project', collection:  @projects, as: :project, locals: { admin: false } %>
  <% else %>
    <%= t("no_suggestions") %>
  <% end %>
  <p>
    <%= link_to t("suggest_project"), new_project_path %>
  </p>
</div>
<hr/>
<%= render partial: "projects/claim" %>

app/views/users/show.html.erb
<div class="title-block profile-title-block row">
  <div class="col-sm-3">
    <%= image_tag(@user.avatar_url(200), :alt => @user.nickname, :class => "profile-avatar") %>
  </div>
  <div class="col-sm-9 profile-details">
    <% if @user == current_user %>
      <div class="profile-actions hidden-xs">
        <div class="row">
          <%= link_to preferences_path, class: "btn btn-default btn-sm" do %>
            <%= octicon "gear", :height => 16 %>
            <%= t("navigation.preferences") %>
          <% end %>
          <%= link_to pull_request_download_path, :id => 'fetch-pull-requests', :class => 'btn btn-info btn-sm', :rel => 'tooltip', :title => t('pull_request.download.tooltip') do %>
            <%= image_tag('spinner.gif', :id => 'spinner', :alt => ' ') %>
            <%= t('dashboard.synchronize') %>
          <% end %>
        </div>
        <div class="row pull-right">
          <% if current_user.twitter_linked? %>
            <%= link_to t("preferences.remove"), twitter_remove_path, method: :delete, class: 'btn btn-danger btn-sm' %>
          <% else %>
            <%= link_to t('twitter.link_account.text'), '/auth/twitter', :class => 'btn btn-info btn-sm', rel: 'tooltip', title: t('twitter.link_account.tooltip') %>
          <% end %>
        </div>
      </div>
    <% end %>
    <h2 class="username"><%= @user.nickname %></h2>
    <div class="profile-item">
      <% if @user.twitter_nickname.present? %>
        <a class="twitter-follow-button" href="https://twitter.com/<%= @user.twitter_nickname %>">
          <%= t("follow_user", twitter: @user.twitter_nickname) %>
        </a>
        <script>

          !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");

        </script>
      <% end %>
      <%= github_button @user.nickname %>
    </div>
    <% if @user.skills.any? %>
      <div class="profile-item">
        <span class="tiny-title">
          <%= t("preferred_languages") %>
        </span>
        <% @user.languages.each do |language| %>
          <span class="<%= language.downcase %>">
            <div class="label label-info language">
              <%= link_to language, language_path(language) %>
            </div>
          </span>
        <% end %>
      </div>
    <% end %>
    <% if @user.organisations.any? %>
      <div class="profile-item">
        <span class="tiny-title">
          <%= t('user.organisations') %>
        </span>
        <ul class="avatar-list avatar-list-xs">
          <% @user.organisations.each do |organisation| %>
            <li class="avatar-cell">
              <%= link_to organisation_path(organisation.login), class: "avatar-link", rel: "tooltip", title: organisation.login, data: { placement: "bottom" } do %>
                <%= image_tag(organisation.avatar_url, alt: organisation.login, class: "avatar-img") %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="profile-pull-request-count">
      <%= octicon "gift" %>
      <%= t("user.contribution_count", user: @user.nickname, count: @user.contributions_ignoring_organisations.year(current_year).count, year: current_year) %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <% if @user.gifts.year(current_year).any? or @user.contributions_ignoring_organisations.year(current_year).any? or @merged_contributions.any? %>
      <ul class="nav nav-tabs" id="presents">
        <% if @user.gifts.year(current_year).any? %>
        <li>
          <a class="active" data-toggle="tab" href="#gifts">Gifts</a>
        </li>
        <% end %>
        <% if @user.contributions_ignoring_organisations.year(current_year).any? %>
        <li>
          <a data-toggle="tab" href="#contributions">Contributions</a>
        </li>
        <% end %>
        <% if @merged_contributions.any? %>
        <li>
          <a data-toggle="tab" href="#merged_contributions">Merges</a>
        </li>
        <% end %>
        <% ((Tfpullrequests::Application.current_year) -1).downto(LAUNCH_YEAR) do |year| %>
          <li>
            <a data-toggle="tab" href="#<%= year %>">
              <%= year %>
            </a>
          </li>
        <% end %>
      </ul>
      <div class="tab-content">
        <div class="tab-pane" id="gifts">
          <%= render :partial => 'calendar', :object => @calendar %>
        </div>
        <div class="tab-pane" id="contributions">
          <%= render partial: 'users/contribution', collection: @user.contributions_ignoring_organisations.year(current_year).latest(nil), cache: true %>
        </div>
        <div class="tab-pane" id="merged_contributions">
          <%= render @merged_contributions, cache: true %>
        </div>
        <% ((Tfpullrequests::Application.current_year) -1).downto(LAUNCH_YEAR) do |year| %>
          <div class="tab-pane" id="<%= year %>">
            <%= render partial: 'users/contribution', collection: @user.contributions.year(year), cache: true %>
          </div>
        <% end %>
      </div>
    <% elsif !Contribution.in_date_range? %>
      <div class="alert alert-info">
        24 Pull Requests runs from 1st-24th December, come back then to see
        <%= "#{@user.nickname}'s progress." %>
      </div>
    <% else %>
      <div class="alert alert-warning">
        <%= t("user.no_current_pr_message", user: content_tag(:strong, "@" + @user.nickname), year: current_year).html_safe %>
      </div>
    <% end %>
  </div>
</div>