config/routes.rb
Tfpullrequests::Application.routes.draw do
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unprocessable'
  get '/500', to: 'errors#internal'

  get '/locale/:locale', to: 'dashboards#locale', as: :locale
  resources :gifts, except: [:show]
  resources :users, only: [:show, :index]

  resources :organisations, only: [:show, :index]

  get '/mergers', to: 'users#mergers', as: :mergers
  get '/users/:id', to: 'users#show'
  get '/users/unsubscribe/:token', to: 'users#unsubscribe', as: :user_unsubscribe

  resources :events

  resources :projects do
    collection do
      get :autofill
      post :claim
    end
    member do
      put :reactivate
    end
  end

  resources :contributions do
    collection do
      get :meta
    end
  end

  resources :pull_requests, only: [:index], controller: 'contributions' do
    collection do
      get :meta
    end
  end

  resource :dashboard, only: [:show, :destroy] do
    member do
      get :delete
      delete :destroy
    end
  end
  resource :pull_request_download, only: :create

  get '/resend_confirmation', to: 'dashboards#resend_confirmation_email', as: 'resend_confirmation'
  get '/confirm/:confirmation_token', to: 'dashboards#confirm_email', as: 'confirm_email'

  get '/preferences', to: 'dashboards#preferences', as: 'preferences'
  patch '/preferences/update', to: 'dashboards#update_preferences', as: 'update_preferences'
  get :my_suggestions, to: 'users#projects', as: :my_suggestions

  get '/login',  to: 'sessions#new',     as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/contributors/map', to: 'contributor_map#show'

  get '/auth/twitter/callback',    to: 'twitter#authorize'
  delete '/twitter/remove',         to: 'twitter#remove'

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get '/auth/failure',             to: 'sessions#failure'


  get 'about', to: 'static#about'
  get 'sponsors' => redirect('/about') # old sponsors url
  get 'humans', to: 'static#humans'
  get 'api', to: 'static#api'
  get 'contributing', to: 'static#contributing'
  get '2018', to: 'static#2018'

  get '/unsubscribe', to: 'unsubscribes#new', as: :unsubscribe
  post '/unsubscribe', to: 'unsubscribes#create'

  resources :languages, only: [:show] do
    member do
      get :projects
      get :pull_requests
      get :users
    end
  end

  root to: 'static#homepage'

  get '/email' => redirect('/preferences') # old preferences URL

  get '/:id' => redirect('/users/%{id}') # User public vanity url, must be lowest priority

  namespace :admin do
    post '/dasher', to: 'dasher#new_pull_request'
    resources :projects, only: [:index, :edit, :update, :destroy]
  end
end

app/models/project.rb
class Project < ApplicationRecord
  LANGUAGES = ['ABAP', 'ActionScript', 'Ada', 'Apex', 'AppleScript', 'Arc',
               'Arduino', 'ASP', 'Assembly', 'Augeas', 'AutoHotkey', 'Awk', 'Bluespec',
               'Boo', 'Bro', 'C', 'C#', 'C++', 'Ceylon', 'Chisel', 'CLIPS', 'Clojure',
               'COBOL', 'CoffeeScript', 'ColdFusion', 'Common Lisp', 'Coq',
               'CSS', 'Crystal', 'D', 'Dart', 'DCPU-16 ASM', 'Delphi', 'DOT', 'Dylan', 'eC', 'Ecl',
               'Eiffel', 'Elixir', 'Elm', 'Emacs Lisp', 'Erlang', 'F#',
               'Factor', 'Fancy', 'Fantom', 'Forth', 'FORTRAN', 'Go', 'Gosu',
               'Groovy', 'Haskell', 'Haxe', 'HTML', 'Io', 'Ioke', 'J', 'Java',
               'JavaScript', 'Julia', 'Kotlin', 'Lasso', 'LiveScript', 'Logos',
               'Logtalk', 'Lua', 'M', 'Markdown', 'Matlab', 'Max', 'Mirah',
               'Monkey', 'MoonScript', 'Nemerle', 'Nimrod', 'Nu',
               'Objective-C', 'Objective-J', 'OCaml', 'Omgrofl', 'ooc', 'Opa',
               'OpenEdge ABL', 'Parrot', 'Pascal', 'Perl', 'Perl 6', 'PHP', 'Pike',
               'PogoScript', 'PowerShell', 'Processing', 'Prolog', 'Puppet',
               'Pure Data', 'Python', 'R', 'Racket', 'Ragel in Ruby Host',
               'Rebol', 'Rouge', 'Ruby', 'Rust', 'Scala', 'Scheme', 'Scilab',
               'Self', 'Shell', 'Slash', 'Smalltalk', 'Squirrel',
               'Standard ML', 'SuperCollider', 'SVG', 'Swift', 'Tcl', 'TeX', 'Turing', 'TXL',
               'TypeScript', 'Vala', 'Verilog', 'VHDL', 'VimL', 'Visual Basic',
               'Volt', 'wisp', 'XC', 'XML', 'XProc', 'XQuery', 'XSLT', 'Xtend']

  has_many :project_labels
  has_many :labels, through: :project_labels

  belongs_to :submitted_by, class_name: 'User', foreign_key: :user_id

  validates :description, :github_url, :name, :main_language, presence: true
  validates :github_url, format: { with: /\Ahttps?:\/\/github.com\/[\w-]+\/[\w\.-]+(\/)?\Z/i, message: 'Enter a valid GitHub URL.' }
  validates :github_url, uniqueness: { case_sensitive: false, message: 'Project has already been suggested.' }
  validates_length_of :description, within: 20..200
  validates_inclusion_of :main_language, in: LANGUAGES, message: 'must be a programming language'

  scope :not_owner, ->(user) { where('github_url NOT ILIKE ?', "%github.com/#{user}/%") }
  scope :by_language, ->(language) { where('lower(main_language) =?', language.downcase) }
  scope :by_languages, ->(languages) { where('lower(main_language) IN (?)', languages) }
  scope :by_labels, ->(labels) { joins(:labels).where('labels.name  IN (?)', labels).select('distinct(projects.id), projects.*') }
  scope :active, -> { where(inactive: [false, nil]) }
  scope :featured, -> { active.where(featured: true) }
  accepts_nested_attributes_for :labels, reject_if: proc { |attributes| attributes['id'].blank? }

  paginates_per 20

  def feature!(owner_id)
    update(featured: true, avatar_url: "https://avatars.githubusercontent.com/u/#{owner_id}?v=3")
  end

  def self.find_by_github_repo(repository)
    filter_by_repository(repository).first
  end

  def self.filter_by_repository(repository)
    Project.where('github_url like ?', "%#{repository}%")
  end

  def github_repository
    github_url.gsub(/^(((https|http|git)?:\/\/(www\.)?)|git@)github.com(:|\/)/i, '').gsub(/(\.git|\/)$/i, '')
  end

  def get_github_data(data_type, nickname, token, months_ago, options)
    date = (Time.zone.now - months_ago.months).utc.iso8601
    options.merge! since: date
    GithubClient.new(nickname, token).send(data_type.to_sym, github_repository, options)
  end

  def deactivate!
    update_attribute(:inactive, true)
  end

  def reactivate!
    update_attribute(:inactive, false)
  end

  def issues(nickname, token, months_ago = 6, options = {})
    get_github_data('issues', nickname, token, months_ago, options)
  end

  def commits(nickname, token, months_ago = 3, options = {})
    get_github_data('commits', nickname, token, months_ago, options)
  end

  def repo(nickname, token)
    GithubClient.new(nickname, token).repository(github_repository)
  end

  def score(nickname, token)
    PopularityScorer.new(nickname, token, self).score
  end

  def contribulator_url
    "https://contribulator.24pullrequests.com/#{github_repository}"
  end

  def url
    homepage.presence || github_url
  end
end

app/controllers/admin/projects_controller.rb
module Admin
  class ProjectsController < ApplicationController
    before_action :ensure_logged_in
    before_action :ensure_admin
    before_action :set_project, only: [:edit, :update, :destroy]

    respond_to :html
    respond_to :js, only: :index

    def index
      @projects = Project.order('inactive desc').order(:name).filter_by_repository(repository).page params[:page]

      respond_with @projects
    end

    def edit
    end

    def update
      if @project.update(editable_project_params)
        redirect_to admin_projects_path, notice: 'Project updated successfully!'
      else
        render :edit
      end
    end

    def destroy
      @project.deactivate!

      redirect_back(fallback_location: admin_projects_path, notice: "#{@project.name} has been deactivated.")
    end

    protected

    def editable_project_params
      params.require(:project).permit(:description, :name, :main_language, :github_url, :homepage, :featured)
    end

    def set_project
      @project = Project.find(params[:id])
    end

    def repository
      params[:repository]
    end

    def ensure_admin
      current_user.admin?
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :ensure_logged_in, except: [:index, :filter]
  before_action :set_project, only: [:edit, :update, :destroy, :reactivate]

  respond_to :html
  respond_to :json, only: :index
  respond_to :js, only: [:index, :filter]

  def index
    @labels = labels
    @languages = languages
    session[:filter_options] = search_params.slice(:languages, :labels)
    search = ProjectSearch.new(search_params)
    @projects = search.call.includes(:labels)
    @has_more_projects = search.more?
    respond_with @projects
  end

  def new
    @project = Project.new
    @project.main_language = language if language
  end

  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      redirect_to projects_path
    else
      render :new
    end
  end

  def edit
    redirect_to root_path, notice: "You can't edit this project!" unless @project.present?
  end

  def destroy
    if @project.inactive?
      @project.destroy!
      flash[:notice] = "#{@project.name} has been deleted."
    else
      @project.deactivate!
      flash[:notice] = "#{@project.name} has been deactivated."
    end
    redirect_back(fallback_location: projects_path)
  end

  def update
    if @project.update(editable_project_params)
      redirect_to projects_path(user: current_user), notice: 'Project updated successfully!'
    else
      render :edit
    end
  end

  def reactivate
    @project.reactivate!
    flash[:notice] = "#{@project.name} has been reactivated."
    redirect_back(fallback_location: projects_path)
  end

  def claim
    project = Project.find_by_github_repo(github_url)

    if project.present? && project.submitted_by.nil?
      project.update_attribute(:user_id, current_user.id)
      message = "You have successfully claimed <b>#{github_url}</b>".html_safe
    else
      message = "This repository doesn't exist or belongs to someone else"
    end

    redirect_to my_suggestions_path, notice: message
  end

  def autofill
    url = params[:repo].gsub(/\/$/, '')
    request = repo_with_labels(url)
    render json: request[:data], status: request[:status]
  end

  protected

  def search_params
    { languages: languages, labels: labels, page: params[:page] }
  end

  def repo_with_labels(url)
    RepoWithLabels.new(current_user.github_client, url).call
  end

  def project_params
    params.require(:project).permit(:description, :github_url, :homepage, :name, :main_language, label_ids: [])
  end

  def editable_project_params
    params.require(:project).permit(:description, :name, :main_language, label_ids: [])
  end

  def language
    params[:language]
  end

  def languages
    Array(params.fetch(:project, {}).fetch(:languages, session.fetch(:filter_options, {}).fetch(:languages, (current_user.try(:languages) || []))))
  end

  def labels
    params.fetch(:project, {}).fetch(:labels, [])
  end

  def github_url
    params[:project][:github_url]
  end

  def set_project
    @project = current_user.projects.find_by_id(params[:id])

    redirect_to user_path(current_user), notice: 'You can only edit projects you have suggested!' unless @project.present?
  end
end

app/helpers/project_helper.rb
module ProjectHelper
  def class_for_inactive(project)
    project.inactive ? 'inactive' : ''
  end

  def inactive?(_project)
    content_tag :span, 'inactive', class: 'info'
  end

  def edit_path_for_project(project, admin)
    return edit_admin_project_path(project) if admin
    edit_project_path(project)
  end

  def path_for_project(project, admin)
    return admin_project_path(project) if admin
    project_path(project)
  end

  def avatar_url(project)
    project.avatar_url || 'https://avatars.githubusercontent.com/u/10137?v=3'
  end
end

app/views/projects/_claim.html.erb
<%= t("projects.claim") %>
<br/>
<br/>
<%= simple_form_for Project.new, url: claim_projects_path do |form| %>
  <%= form.input :github_url, wrapper_html: { class:  'col-lg-3 col-md-3' }, :label => false, required: false, placeholder: t("exempli_gratia") + " 24pullrequests/24pullrequests" %>
  <%= form.button :submit, t("claim") %>
<% end %>

app/views/projects/_editable_project.html.erb
<div class="project <%= "#{parameterize_language(project.main_language)} #{class_for_inactive(project)}" %>" data-id="<%= project.id %>">
  <div class="title clearfix">
    <h4>
      <%= project.name %>
      <% if project.inactive? %>
        <small>
          <%= inactive?(project) %>
        </small>
        <%= link_to t("reactivate"), reactivate_project_path(project, admin),
          method: :put,
          class: 'btn btn-info pull-right' %>
        <%= link_to t("delete"), path_for_project(project, admin),
          method: :delete,
          data: { confirm: 'Are you sure you want to delete this project?' },
          class: 'btn btn-danger pull-right' %>
      <% else %>
        <%= link_to t("deactivate"), path_for_project(project, admin),
          method: :delete,
          data: { confirm: "Are you sure you want to deactivate this project?" },
          class: 'btn btn-danger pull-right'%>
      <% end %>
      <%= link_to t("edit"), edit_path_for_project(project, admin), class: 'btn pull-right' %>
    </h4>
    <%= link_to project.github_repository, project.github_url, :target => '_blank' %>
  </div>
  <p class="js-emoji">
    <%= truncate project.description, :length => 200 %>
  </p>
  <div class="language label label-info">
    <%= link_to project.main_language, language_path(project.main_language.downcase) %>
  </div>
  <% project.labels.each do |label| %>
    <div class="project-label">
      <%= octicon "tag" %>
      <%= label.name %>
    </div>
  <% end %>
</div>

app/views/projects/_form.html.erb
<%= simple_form_for @project, wrapper: :bootstrap3_horizontal, defaults: {right_column_html: {class: "col-lg-3 col-md-3"}, label_html: {class: "col-lg-2 col-md-2"} }, :html => {:class => 'form-horizontal', :role => "form"} do |form| %>
  <%= form.input :name, :label => t("projects.new.form.project_name") %>
  <%= form.input :github_url, disabled: @project.persisted?, :label => t("projects.new.form.github_url") %>
  <%= form.input :description, :input_html => {:rows => 5}, :label => t("projects.new.form.summary") %>
  <%= form.input :main_language, :collection => Project::LANGUAGES, :label => t("projects.new.form.main_language") %>
  <%= form.association :labels, collection: Label.all, as: :check_boxes %>
  <div class="form-group">
    <div class="col-md-offset-2 col-sm-10">
      <%= form.button :submit, t("projects.new.form.submit_project") %>
      <%= t("or") %>
      <%= link_to t("cancel"), projects_path %>
    </div>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div class="project <%= parameterize_language(project.main_language) %>" data-id="<%= project.id %>">
  <% if defined?(show_avatar) && show_avatar %>
    <%= link_to image_tag(avatar_url(project), :width => 80, :height => 80), project.url, :rel => 'tooltip', :data => { :original_title => project.name }, :class => 'image' %>
  <% end %>
  <div class="language label label-info pull-right">
    <%= link_to project.main_language, language_path(project.main_language.downcase) %>
  </div>
  <%= link_to project.url, :target => "_blank", :title => project.github_repository, :class => "project-link" do %>
    <span class="project-title">
      <%= project.name %>
    </span>
    <p class="js-emoji">
      <%= project.description %>
    </p>
  <% end %>
  <% project.labels.each do |label| %>
    <div class="project-label">
      <%= octicon "tag", :height => 10 %>
      <%= link_to label.name, "#{project.url}/labels/#{label.name}", target: "_blank" %>
    </div>
  <% end %>
  <% unless project.contribulator.blank? %>
    <div class="project-label">
      <%= octicon "pulse", :height => 10 %>
      <%= link_to "Contribulator score: #{project.contribulator}", project.contribulator_url, class: 'contribulator', target: '_blank' %>
    </div>
  <% end %>
</div>

app/views/projects/edit.html.erb
<h3>
  <%= t("projects.edit.title") %>
</h3>
<%= render partial: 'projects/form' %>

app/views/projects/index.html.erb
<h2>
  <%= number_with_delimiter Project.active.count %>
  <%= t("suggested_projects") %>
  <%= link_to t("suggest_project"), new_project_path, :class => 'btn btn-default pull-right' %>
</h2>
<p>
  <%= t("projects.help_out") %>
</p>
<p>
  <%= t("projects.suggest_new") %>
</p>
<hr/>

<h4>Filter:</h4>
<%= simple_form_for :project, url: projects_path, method: :get, remote: true, html: { id: 'filters' }  do |form| %>

  <div class="icheckbox_line checked" id="clear_labels">All Labels</div>
  <% labels_collection = Label.distinct.pluck(:name).sort%>
  <%= form.input :labels, collection: labels_collection, as: :check_boxes, label_method: lambda { |owner| content_tag(:span, owner) }, label: false, checked: lambda { |v| @labels.include?(v) } %>

  <div class="icheckbox_line checked" id="clear_languages">All Languages</div>
  <% lang_collection = Project.distinct.pluck(:main_language).sort %>
  <%= form.input :languages, collection: lang_collection, as: :check_boxes, label_method: lambda { |owner| content_tag(:span, owner) }, label: false, checked: lambda { |v| @languages.include?(v) } %>
  <%= form.submit "Search" %>
<% end %>
<hr/>

<div class="row" id="projects">
  <div class="col-md-12">
    <%= render @projects %>
  </div>
</div>

<% if @has_more_projects %>
  <div class="row" id="someprojects">
    <div class="col-md-12">
      <%= link_to_next_page @projects, t("more"), remote: true, class: 'btn btn-success more' %>
    </div>
  </div>
<% end %>

<div id="noprojects">
  <p>
    <%= t("projects.suggest", suggest_link: link_to(t("projects.suggest_link_text"), new_project_path)).html_safe %>
  </p>
</div>

app/views/projects/index.js.erb
<% if @projects.any? %>
  (function($projects) {
    var $new = $("<%= escape_javascript(render(@projects)) %>");

    $projects.find('.col-md-12')['<%= params[:page].blank? ? "html" : "append" %>']($new)

    $('#someprojects').find('.col-md-12')
      .html(
        "<%= escape_javascript(link_to_next_page @projects,
                                               t('more'),
                                               remote: true,
                                               params: {project: {languages: @languages, labels: @labels}},
                                               class: 'btn btn-success more') %>"
      );
  })($("#projects"));
  $('#noprojects').hide()
  $('#someprojects').show()
<% else %>
  $('#projects').find('.col-md-12').empty()
  $('#noprojects').show()
  $('#someprojects').hide()
<% end %>

app/views/projects/new.html.erb
<h2>
  <%= t("projects.new.title") %>
</h2>
<p>
  <%= t("projects.new.info") %>
</p>
<%= render partial: 'form' %>
<p>
  <%= t("projects.new.suggestion", issue_link: link_to(t("projects.new.issue_link_text"), 'https://github.com/24pullrequests/24pullrequests/issues')).html_safe %>
</p>