config/routes.rb
Tfpullrequests::Application.routes.draw do
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unprocessable'
  get '/500', to: 'errors#internal'

  get '/locale/:locale', to: 'dashboards#locale', as: :locale
  resources :gifts, except: [:show]
  resources :users, only: [:show, :index]

  resources :organisations, only: [:show, :index]

  get '/mergers', to: 'users#mergers', as: :mergers
  get '/users/:id', to: 'users#show'
  get '/users/unsubscribe/:token', to: 'users#unsubscribe', as: :user_unsubscribe

  resources :events

  resources :projects do
    collection do
      get :autofill
      post :claim
    end
    member do
      put :reactivate
    end
  end

  resources :contributions do
    collection do
      get :meta
    end
  end

  resources :pull_requests, only: [:index], controller: 'contributions' do
    collection do
      get :meta
    end
  end

  resource :dashboard, only: [:show, :destroy] do
    member do
      get :delete
      delete :destroy
    end
  end
  resource :pull_request_download, only: :create

  get '/resend_confirmation', to: 'dashboards#resend_confirmation_email', as: 'resend_confirmation'
  get '/confirm/:confirmation_token', to: 'dashboards#confirm_email', as: 'confirm_email'

  get '/preferences', to: 'dashboards#preferences', as: 'preferences'
  patch '/preferences/update', to: 'dashboards#update_preferences', as: 'update_preferences'
  get :my_suggestions, to: 'users#projects', as: :my_suggestions

  get '/login',  to: 'sessions#new',     as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/contributors/map', to: 'contributor_map#show'

  get '/auth/twitter/callback',    to: 'twitter#authorize'
  delete '/twitter/remove',         to: 'twitter#remove'

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get '/auth/failure',             to: 'sessions#failure'


  get 'about', to: 'static#about'
  get 'sponsors' => redirect('/about') # old sponsors url
  get 'humans', to: 'static#humans'
  get 'api', to: 'static#api'
  get 'contributing', to: 'static#contributing'
  get '2018', to: 'static#2018'

  get '/unsubscribe', to: 'unsubscribes#new', as: :unsubscribe
  post '/unsubscribe', to: 'unsubscribes#create'

  resources :languages, only: [:show] do
    member do
      get :projects
      get :pull_requests
      get :users
    end
  end

  root to: 'static#homepage'

  get '/email' => redirect('/preferences') # old preferences URL

  get '/:id' => redirect('/users/%{id}') # User public vanity url, must be lowest priority

  namespace :admin do
    post '/dasher', to: 'dasher#new_pull_request'
    resources :projects, only: [:index, :edit, :update, :destroy]
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :ensure_logged_in, except: [:confirm_email, :locale]
  before_action :set_email_preferences, except: [:preferences, :update_preferences, :confirm_email, :locale]

  def show
    contributions = current_user
      .contributions_ignoring_organisations
      .year(current_year)
      .order('created_at desc')
      .to_a

    projects      = current_user.suggested_projects.order(Arel.sql("RANDOM()")).limit(12).sort_by(&:name)
    gifted_today  = current_user.gift_for(today)
    @events = Event.where(['start_time >= ?', Time.zone.today]).order('start_time').first(5)

    if giftable_range? && current_user.unspent_contributions.any? && !gifted_today
      gift      = current_user.new_gift
      gift_form = GiftForm.new(gift: gift, contributions: current_user.unspent_contributions)
    end

    @contribution = current_user.contributions.build

    render :show, locals: { user:          current_user,
                            contributions: contributions,
                            projects:      projects,
                            gift_form:     gift_form }
  end

  def preferences
    session[:preferences_referrer] = request.referrer unless current_user.email_frequency.nil?
  end

  def update_preferences
    current_user.skills.delete_all
    if current_user.update(user_params)
      redirect_to(session[:preferences_referrer] || dashboard_path, notice: 'Your preferences were successfully saved')
      session.delete(:preferences_referrer)
    else
      render :preferences
    end
  end

  def destroy
    current_user.destroy
    session.delete(:user_id)
    redirect_to root_path, notice: 'Your account was successfully deleted'
  end

  def resend_confirmation_email
    current_user.send_confirmation_email
    redirect_back(fallback_location: dashboard_path, notice: 'Confirmation email sent. Please check your inbox.')
  end

  def confirm_email
    if params[:confirmation_token].present?
      user = User.where(confirmation_token: params[:confirmation_token]).first

      if user.present?
        user.confirm!
        flash[:notice] = 'Email address confirmed'
      else
        flash[:notice] = 'Unknown confirmation token'
      end
    end

    redirect_to root_path
  end

  def locale
    set_locale_to_cookie params[:locale]
    redirect_back(fallback_location: root_path)
  end

  protected

  def today
    Time.zone.now.to_date
  end

  def giftable_range?
    today > Date.new(Tfpullrequests::Application.current_year, 12, 1) && today < Date.new(Tfpullrequests::Application.current_year, 12, 24)
  end

  def set_email_preferences
    redirect_to preferences_path unless current_user.email_frequency.present?
  end

  def user_params
    params.require(:user).permit(:uid, :provider, :nickname, :email, :gravatar_id, :token, :email_frequency, :twitter_token, :ignored_organisations_string, skills_attributes: [:language])
  end

  def set_locale_to_cookie(locale)
    cookies[:locale] = { value:   locale,
                         expires: Time.zone.now + 36_000 }
  end
end

app/views/dashboards/_contributions_if_any.html.erb
<% if current_user.contributions.year(current_year).any? %>
  <%= render :partial => 'contributions/contribution', :collection => contributions, cache: true %>
<% elsif DateTime.new(current_year, 12, 1) > DateTime.now %>
  <p>
    <%= t('dashboard.not_december') %>
  </p>
<% else %>
  <p>
    <%= t("dashboard.no_pull_requests") %>
  </p>
<% end %>

app/views/dashboards/delete.html.erb
<h1>
  <%= t("delete_account.title") %>
</h1>
<p>
  <%= t("delete_account.are_you_sure") %>
</p>
<p>
  <%= t("delete_account.notification_info", email_preferences_link: link_to(t("email_preferences_link"), preferences_path)).html_safe %>
</p>
<p>
  <%= link_to t("delete_account.confirm"), dashboard_path, :method => :delete, :class => 'btn' %>
  or
  <%= link_to t("delete_account.cancel"), dashboard_path %>
</p>

app/views/dashboards/preferences.html.erb
<div class="title-block">
  <% if current_user.needs_setup? %>
    <h1 class="block-title">
      <%= t("welcome", user: current_user.nickname) %>
    </h1>
    <%= t("preferences.setup_help") %>
  <% else %>
    <h1 class="block-title">
      <%= t("preferences.title", user: current_user.nickname) %>
    </h1>
  <% end %>
</div>
<div class="row">
  <%= simple_form_for current_user, :url => update_preferences_path, wrapper: :bootstrap3_horizontal, defaults: {right_column_html: {class: "col-md-8"}, label_html: {class: "col-md-4"} }, :html => {:class => 'block form-horizontal', :role => "form"}  do |form| %>
    <div class="col-md-6 col-md-offset-3">
      <p>
        <%= t("preferences.frequency_message") %>
      </p>
      <% if current_user.email_frequency.present? %>
        <small>
          <%= link_to t("preferences.delete"), delete_dashboard_path, :class => 'pull-right' %>
        </small>
      <% end %>
      <p>
        <em>
          <%= t("preferences.information") %>
        </em>
      </p>
      <%= form.input :email_frequency, :label => t("preferences.form.email_frequency"), :collection => [[t("preferences.form.never"), 'none'], [t("preferences.form.daily"), 'daily'], [t("preferences.form.weekly"), 'weekly']], :selected => (form.object.email_frequency || 'daily') %>
      <% if current_user.email.present? && !current_user.confirmed? %>
        <%= form.input :email, hint: t("preferences.hint.confirm_email") %>
      <% else %>
        <%= form.input :email, :label => t("preferences.form.email") %>
      <% end %>
      <p>
        <%= t("preferences.ignore_organisations") %>
      </p>
      <%= form.input :ignored_organisations_string, label: t("preferences.ignored_organisations"), placeholder: "e.g. 24pullrequests, alphagov", input_html: {class: "pull-left"} %>
    </div>
    <div class="col-md-12">
      <h2 class="text-center">
        <%= t("preferences.languages") %>
      </h2>
      <div class="row">
        <% Project::LANGUAGES.in_groups(2, false) do |main_col| %>
          <div class="col-xs-12 col-sm-6">
            <% main_col.in_groups(3, false) do |col_form| %>
              <div class="col-xs-12 col-md-4">
                <%= form.simple_fields_for :skills, col_form.map{|l| Skill.new(:language => l)} do |skill_form| %>
                  <% language = skill_form.object.language %>
                  <div class="col-md-12">
                    <label class="language-checkbox">
                      <%= skill_form.check_box :language, {:id => language, :checked => current_user.skills.map(&:language).include?(language)}, language %>
                      <%= language %>
                    </label>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-12 text-center">
        <% if current_user.needs_setup? %>
          <%= form.button :submit, t("preferences.save_and_continue") %>
        <% else %>
          <%= form.button :submit, t("preferences.save") %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/dashboards/show.html.erb
<div class="title-block">
  <h2 class="block-title">
    <%= t("welcome_back", user: user.nickname) %>
  </h2>
  <%= t("dashboard.christmas_activity") %>
</div>

<div class="row">
  <div class="alert alert-info">
    This year we're making 24 Pull Requests more inclusive and open to all kinds of contributions -
    <%= link_to "Click here to see what's changed", '/2018' %>
  </div>
</div>

<% if Contribution.in_date_range? %>
<div class="row">
  <div class="col-md-12">
    <h3>
      <%= t("contributions.new.title") %>
    </h3>
    <%= render 'contributions/form' %>
    <hr>
  </div>
</div>
<% end %>

<div class="row">
  <div class="col-md-12">
    <div class="user-pull-requests">
      <div class="pull-right mobile-no-float">
        <%= link_to preferences_path, class: "btn btn-default btn-sm" do %>
          <%= octicon "gear", :height => 16 %>
          <%= t("navigation.preferences") %>
        <% end %>
        <%= link_to pull_request_download_path, :id => 'fetch-pull-requests', :class => 'btn btn-info btn-sm', :rel => 'tooltip', :title => t('pull_request.download.tooltip') do %>
          <%= image_tag('spinner.gif', :id => 'spinner', :alt => ' ') %>
          <%= t('dashboard.synchronize') %>
        <% end %>
      </div>
      <% if contributions.any? %>
        <h3>
          <%= t("your_pull_requests") %>
          <% if contributions.any? %>
            <span class="label label-info" id="pull-requests-count">
              <%= contributions.count %>
            </span>
            <a class="twitter-share-button" data-url="<%= user_url(user) %>" data-hashtags="24pr" data-text="<%= t("dashboard.tweet_progress", count: contributions.count) %>" data-via="24pullrequests" href="https://twitter.com/share">Tweet</a>
            <script>

              !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");

            </script>
          <% end %>
        </h3>
      <% end %>
      <div class="clearfix" id="pull-requests">
        <%= render :partial => 'contributions_if_any', :locals => { :contributions => contributions } %>
      </div>
    </div>
    <div class="pull-right mobile-no-float">
      <%= link_to t("view_all"), projects_path, :class => 'btn btn-default btn-sm' %>
      <%= link_to t("suggest_project"), new_project_path, :class => 'btn btn-info btn-sm' %>
    </div>
    <h3>
      <%= t("suggested_projects") %>
    </h3>
    <p>
      <%= t("dashboard.help_out") %>
    </p>
    <div id="projects">
      <%= render projects %>
    </div>
  </div>
  <div class="col-md-4">
    <% if @events.any? %>
      <div class="sidebar-block">
        <h4 class="block-title">
          <%= t("homepage.event.title") %>
        </h4>
        <% @events.each do |event| %>
          <div class="event-item">
            <strong>
              <%= link_to event.name, event %>
            </strong>
            <br/>
            <small>
              <%= octicon "location", :height => 12 %>
              <%= event.location %>
              <br/>
              <%= octicon "clock", :height => 12 %>
              <%= event.formatted_date %>
            </small>
          </div>
        <% end %>
        <%= link_to t("view_all"), events_path, :class => 'btn btn-sm btn-default btn-block' %>
      </div>
    <% end %>
  </div>
</div>